"""Baseline: the schema as it stood before the biometric/payroll-rules upgrade.

Databases created by the earlier `create_all` startup are stamped with this
revision rather than re-created, so existing data survives the switch.

Originally: baseline schema

Revision ID: 2ae4e17a1e86
Revises:
Create Date: 2026-09-10 11:09:55.390316
"""

import sqlalchemy as sa
from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenants_code"), ["code"], unique=True)

    op.create_table(
        "biometric_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("device_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("brand", sa.String(length=80), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("api_key_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("CONNECTED", "DISCONNECTED", "ERROR", name="devicestatus"),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "device_code", name="uq_device_tenant_code"),
    )
    with op.batch_alter_table("biometric_devices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_biometric_devices_device_code"), ["device_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_biometric_devices_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_dept_tenant_name"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_departments_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "designations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_desig_tenant_name"),
    )
    with op.batch_alter_table("designations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_designations_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "holidays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "holiday_date", name="uq_holiday_tenant_date"),
    )
    with op.batch_alter_table("holidays", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_holidays_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "leave_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("annual_quota_days", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_leavetype_tenant_name"),
    )
    with op.batch_alter_table("leave_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leave_types_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "salary_structures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("overtime_rate_per_hour", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_struct_tenant_name"),
    )
    with op.batch_alter_table("salary_structures", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_salary_structures_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.Column("grace_minutes", sa.Integer(), nullable=False),
        sa.Column("half_day_hours", sa.Float(), nullable=False),
        sa.Column("full_day_hours", sa.Float(), nullable=False),
        sa.Column("overtime_after_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_shift_tenant_name"),
    )
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shifts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "tenant_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", name="uq_setting_tenant_key"),
    )
    with op.batch_alter_table("tenant_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_settings_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_code", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("date_of_joining", sa.Date(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("designation_id", sa.Integer(), nullable=True),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.Column(
            "employment_type",
            sa.Enum("FULL_TIME", "PART_TIME", "CONTRACT", name="employmenttype"),
            nullable=False,
        ),
        sa.Column("shift_id", sa.Integer(), nullable=True),
        sa.Column("bank_account", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "TERMINATED", name="employeestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["designation_id"],
            ["designations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "employee_code", name="uq_emp_tenant_code"),
    )
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employees_employee_code"), ["employee_code"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_employees_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "salary_components",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("structure_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "component_type", sa.Enum("EARNING", "DEDUCTION", name="componenttype"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("percent_of_basic", sa.Float(), nullable=True),
        sa.Column("prorated", sa.Boolean(), nullable=False),
        sa.Column("is_basic", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["salary_structures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("salary_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_salary_components_structure_id"), ["structure_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_salary_components_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "sync_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("received", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["biometric_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_logs_device_id"), ["device_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sync_logs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "attendance_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.Enum("CHECK_IN", "CHECK_OUT", name="eventtype"), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("WEBAUTHN", "BIOMETRIC_DEVICE", "MOCK_DEVICE", "MANUAL", name="eventsource"),
            nullable=False,
        ),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("credential_id", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("external_ref", sa.String(length=128), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["biometric_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "external_ref", name="uq_event_tenant_external_ref"),
    )
    with op.batch_alter_table("attendance_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_events_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_events_event_time"), ["event_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_events_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "biometric_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("device_user_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["biometric_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "device_user_id", name="uq_biouser_device_user"),
    )
    with op.batch_alter_table("biometric_users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_biometric_users_device_id"), ["device_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_biometric_users_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_biometric_users_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "daily_attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=True),
        sa.Column("first_in", sa.DateTime(), nullable=True),
        sa.Column("last_out", sa.DateTime(), nullable=True),
        sa.Column("worked_minutes", sa.Integer(), nullable=False),
        sa.Column("late_minutes", sa.Integer(), nullable=False),
        sa.Column("early_leave_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PRESENT",
                "ABSENT",
                "HALF_DAY",
                "ON_LEAVE",
                "HOLIDAY",
                "WEEKLY_OFF",
                name="attendancestatus",
            ),
            nullable=False,
        ),
        sa.Column("payable_day_fraction", sa.Float(), nullable=False),
        sa.Column("missing_checkout", sa.Boolean(), nullable=False),
        sa.Column("is_manual_override", sa.Boolean(), nullable=False),
        sa.Column("remarks", sa.String(length=255), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "employee_id", "work_date", name="uq_daily_emp_date"),
    )
    with op.batch_alter_table("daily_attendance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_daily_attendance_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_daily_attendance_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_daily_attendance_work_date"), ["work_date"], unique=False
        )

    op.create_table(
        "employee_salary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("structure_id", sa.Integer(), nullable=False),
        sa.Column("monthly_ctc", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("overtime_rate_per_hour", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["salary_structures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("employee_salary", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employee_salary_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_employee_salary_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "employee_shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("employee_shifts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employee_shifts_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_employee_shifts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "HR", "MANAGER", "EMPLOYEE", name="role"), nullable=False
        ),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_user_tenant_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "webauthn_challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("challenge", sa.LargeBinary(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webauthn_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webauthn_challenges_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_webauthn_challenges_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "webauthn_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.String(length=512), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("credential_type", sa.String(length=32), nullable=False),
        sa.Column("transports", sa.String(length=160), nullable=True),
        sa.Column("device_label", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webauthn_credentials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webauthn_credentials_credential_id"), ["credential_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_webauthn_credentials_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_webauthn_credentials_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "enrollment_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("enrollment_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_enrollment_tokens_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_enrollment_tokens_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_enrollment_tokens_token"), ["token"], unique=True)

    op.create_table(
        "leave_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("leave_type_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "CANCELLED", name="leavestatus"),
            nullable=False,
        ),
        sa.Column("decided_by_user_id", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decision_note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leave_type_id"],
            ["leave_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_leave_requests_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_leave_requests_end_date"), ["end_date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_leave_requests_start_date"), ["start_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leave_requests_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "payroll_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "CALCULATED", "UNDER_REVIEW", "APPROVED", "PROCESSED", name="payrollstatus"
            ),
            nullable=False,
        ),
        sa.Column("gross_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deduction_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("net_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("calculated_at", sa.DateTime(), nullable=True),
        sa.Column("approved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "period_year", "period_month", name="uq_run_tenant_period"
        ),
    )
    with op.batch_alter_table("payroll_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payroll_runs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "payroll_adjustments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column(
            "component_type", sa.Enum("EARNING", "DEDUCTION", name="componenttype"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["payroll_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payroll_adjustments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payroll_adjustments_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payroll_adjustments_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payroll_adjustments_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "payroll_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("working_days", sa.Float(), nullable=False),
        sa.Column("payable_days", sa.Float(), nullable=False),
        sa.Column("lop_days", sa.Float(), nullable=False),
        sa.Column("paid_leave_days", sa.Float(), nullable=False),
        sa.Column("overtime_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("gross", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deductions", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("net", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("breakdown_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["payroll_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "employee_id", name="uq_item_run_employee"),
    )
    with op.batch_alter_table("payroll_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payroll_items_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payroll_items_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payroll_items_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "payslips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("payslip_number", sa.String(length=64), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["payroll_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payslip_number"),
        sa.UniqueConstraint("run_id", "employee_id", name="uq_payslip_run_employee"),
    )
    with op.batch_alter_table("payslips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payslips_employee_id"), ["employee_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payslips_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payslips_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payslips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payslips_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payslips_run_id"))
        batch_op.drop_index(batch_op.f("ix_payslips_employee_id"))

    op.drop_table("payslips")
    with op.batch_alter_table("payroll_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payroll_items_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_items_run_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_items_employee_id"))

    op.drop_table("payroll_items")
    with op.batch_alter_table("payroll_adjustments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payroll_adjustments_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_adjustments_run_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_adjustments_employee_id"))

    op.drop_table("payroll_adjustments")
    with op.batch_alter_table("payroll_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payroll_runs_tenant_id"))

    op.drop_table("payroll_runs")
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leave_requests_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_leave_requests_start_date"))
        batch_op.drop_index(batch_op.f("ix_leave_requests_end_date"))
        batch_op.drop_index(batch_op.f("ix_leave_requests_employee_id"))

    op.drop_table("leave_requests")
    with op.batch_alter_table("enrollment_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enrollment_tokens_token"))
        batch_op.drop_index(batch_op.f("ix_enrollment_tokens_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_enrollment_tokens_employee_id"))

    op.drop_table("enrollment_tokens")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("webauthn_credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webauthn_credentials_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_webauthn_credentials_employee_id"))
        batch_op.drop_index(batch_op.f("ix_webauthn_credentials_credential_id"))

    op.drop_table("webauthn_credentials")
    with op.batch_alter_table("webauthn_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webauthn_challenges_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_webauthn_challenges_employee_id"))

    op.drop_table("webauthn_challenges")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("employee_shifts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_shifts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_employee_shifts_employee_id"))

    op.drop_table("employee_shifts")
    with op.batch_alter_table("employee_salary", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_salary_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_employee_salary_employee_id"))

    op.drop_table("employee_salary")
    with op.batch_alter_table("daily_attendance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_attendance_work_date"))
        batch_op.drop_index(batch_op.f("ix_daily_attendance_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_daily_attendance_employee_id"))

    op.drop_table("daily_attendance")
    with op.batch_alter_table("biometric_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biometric_users_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_biometric_users_employee_id"))
        batch_op.drop_index(batch_op.f("ix_biometric_users_device_id"))

    op.drop_table("biometric_users")
    with op.batch_alter_table("attendance_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_events_event_time"))
        batch_op.drop_index(batch_op.f("ix_attendance_events_employee_id"))

    op.drop_table("attendance_events")
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_logs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_sync_logs_device_id"))

    op.drop_table("sync_logs")
    with op.batch_alter_table("salary_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_salary_components_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_salary_components_structure_id"))

    op.drop_table("salary_components")
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employees_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_employees_employee_code"))

    op.drop_table("employees")
    with op.batch_alter_table("tenant_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_settings_tenant_id"))

    op.drop_table("tenant_settings")
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shifts_tenant_id"))

    op.drop_table("shifts")
    with op.batch_alter_table("salary_structures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_salary_structures_tenant_id"))

    op.drop_table("salary_structures")
    with op.batch_alter_table("leave_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leave_types_tenant_id"))

    op.drop_table("leave_types")
    with op.batch_alter_table("holidays", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_holidays_tenant_id"))

    op.drop_table("holidays")
    with op.batch_alter_table("designations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_designations_tenant_id"))

    op.drop_table("designations")
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_tenant_id"))

    op.drop_table("departments")
    with op.batch_alter_table("biometric_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biometric_devices_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_biometric_devices_device_code"))

    op.drop_table("biometric_devices")
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_code"))

    op.drop_table("tenants")
    # ### end Alembic commands ###
