"""biometric status, payroll rules, payslip templates

Revision ID: 53cfe9e01d54
Revises: 0001_baseline
Create Date: 2026-09-10 11:11:08.752660
"""

import sqlalchemy as sa
from alembic import op

revision = "0002_biometric_payroll_config"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payroll_rule_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payroll_rule_sets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payroll_rule_sets_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "payslip_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("template_data", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payslip_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payslip_templates_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "payroll_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("rule_set_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("EARNING", "DEDUCTION", "INTERMEDIATE", name="ruletype"),
            nullable=False,
        ),
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("show_on_payslip", sa.Boolean(), nullable=False),
        sa.Column("show_if_zero", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_id"],
            ["payroll_rule_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_set_id", "code", "version", name="uq_rule_set_code_version"),
    )
    with op.batch_alter_table("payroll_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payroll_rules_code"), ["code"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payroll_rules_rule_set_id"), ["rule_set_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payroll_rules_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "biometric_status",
                sa.Enum(
                    "NOT_REGISTERED",
                    "PENDING_VERIFICATION",
                    "VERIFIED",
                    "DISABLED",
                    name="biometricstatus",
                ),
                nullable=False,
                server_default="NOT_REGISTERED",
            )
        )
        batch_op.add_column(sa.Column("biometric_registered_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("biometric_verified_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("biometric_verified_by_user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("biometric_note", sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(
            "fk_employees_biometric_verified_by", "users", ["biometric_verified_by_user_id"], ["id"]
        )

    with op.batch_alter_table("payroll_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rule_set_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("rule_set_version", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_payroll_runs_rule_set", "payroll_rule_sets", ["rule_set_id"], ["id"]
        )

    with op.batch_alter_table("payslips", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("template_version", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("template_snapshot_json", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("pdf_reference", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column(
                "gross_salary",
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "total_deductions",
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "net_salary", sa.Numeric(precision=12, scale=2), nullable=False, server_default="0"
            )
        )
        batch_op.add_column(sa.Column("regenerated_at", sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            "fk_payslips_template", "payslip_templates", ["template_id"], ["id"]
        )

    with op.batch_alter_table("webauthn_credentials", schema=None) as batch_op:
        batch_op.add_column(sa.Column("device_name", sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("ACTIVE", "REVOKED", name="credentialstatus"),
                nullable=False,
                server_default="ACTIVE",
            )
        )
        batch_op.add_column(sa.Column("revoked_at", sa.DateTime(), nullable=True))

    _backfill_existing_data()
    # ### end Alembic commands ###


def _backfill_existing_data() -> None:
    """Carry existing state forward.

    Employees who already hold an active WebAuthn credential were checking in
    before this upgrade, so they are marked VERIFIED - anything else would
    lock them out of attendance the moment the migration ran. Everyone else
    starts at NOT_REGISTERED, which the column default already gives them.

    Payslip totals are lifted out of the JSON snapshot that held them before
    they became columns.
    """
    connection = op.get_bind()

    connection.execute(sa.text("""
            UPDATE employees
               SET biometric_status = 'VERIFIED',
                   biometric_registered_at = (
                       SELECT MIN(created_at) FROM webauthn_credentials c
                        WHERE c.employee_id = employees.id AND c.is_active = 1
                   ),
                   biometric_verified_at = (
                       SELECT MIN(created_at) FROM webauthn_credentials c
                        WHERE c.employee_id = employees.id AND c.is_active = 1
                   ),
                   biometric_note = 'Verified on upgrade: credential predates verification'
             WHERE EXISTS (
                       SELECT 1 FROM webauthn_credentials c
                        WHERE c.employee_id = employees.id AND c.is_active = 1
                   )
            """))

    connection.execute(
        sa.text("UPDATE webauthn_credentials SET status = 'REVOKED' WHERE is_active = 0")
    )
    connection.execute(
        sa.text(
            "UPDATE webauthn_credentials SET device_name = device_label WHERE device_name IS NULL"
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webauthn_credentials", schema=None) as batch_op:
        batch_op.drop_column("revoked_at")
        batch_op.drop_column("status")
        batch_op.drop_column("device_name")

    with op.batch_alter_table("payslips", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("regenerated_at")
        batch_op.drop_column("net_salary")
        batch_op.drop_column("total_deductions")
        batch_op.drop_column("gross_salary")
        batch_op.drop_column("pdf_reference")
        batch_op.drop_column("template_snapshot_json")
        batch_op.drop_column("template_version")
        batch_op.drop_column("template_id")

    with op.batch_alter_table("payroll_runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_payroll_runs_rule_set", type_="foreignkey")
        batch_op.drop_column("rule_set_version")
        batch_op.drop_column("rule_set_id")

    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_constraint("fk_employees_biometric_verified_by", type_="foreignkey")
        batch_op.drop_column("biometric_note")
        batch_op.drop_column("biometric_verified_by_user_id")
        batch_op.drop_column("biometric_verified_at")
        batch_op.drop_column("biometric_registered_at")
        batch_op.drop_column("biometric_status")

    with op.batch_alter_table("payroll_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payroll_rules_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_rules_rule_set_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_rules_code"))

    op.drop_table("payroll_rules")
    with op.batch_alter_table("payslip_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payslip_templates_tenant_id"))

    op.drop_table("payslip_templates")
    with op.batch_alter_table("payroll_rule_sets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payroll_rule_sets_tenant_id"))

    op.drop_table("payroll_rule_sets")
    # ### end Alembic commands ###
