"""Statutory identifiers and branch on the employee record.

All nullable: a restaurant may employ staff outside PF/ESI, and existing rows
simply carry no value.

Originally: employee statutory identifiers

Revision ID: 01903c3be227
Revises: 0002_biometric_payroll_config
Create Date: 2026-09-11 08:57:50.727073
"""

import sqlalchemy as sa
from alembic import op

revision = "0003_employee_statutory_ids"
down_revision = "0002_biometric_payroll_config"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bank_ifsc", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("branch", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("pan", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("pf_number", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("esi_number", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("uan", sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_column("uan")
        batch_op.drop_column("esi_number")
        batch_op.drop_column("pf_number")
        batch_op.drop_column("pan")
        batch_op.drop_column("branch")
        batch_op.drop_column("bank_ifsc")

    # ### end Alembic commands ###
